# Generated by Django 5.2.8 on 2026-04-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioproyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='miembros',
            field=models.ManyToManyField(related_name='proyectos', through='proyectos.UsuarioProyecto', to=settings.AUTH_USER_MODEL, verbose_name='Miembros'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioproyecto',
            unique_together={('usuario', 'proyecto')},
        ),
    ]
