# Generated by Django 5.2.8 on 2026-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_add_creador_to_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioproyecto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Deshabilita al miembro sin borrar su historial de tareas.', verbose_name='Activo en el proyecto'),
        ),
    ]
