# Generated by Django 5.2.8 on 2026-04-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='tareas', through='tareas.TareaUsuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asignados'),
        ),
        migrations.AlterUniqueTogether(
            name='tareaetiqueta',
            unique_together={('tarea', 'etiqueta')},
        ),
        migrations.AlterUniqueTogether(
            name='tareausuario',
            unique_together={('tarea', 'usuario')},
        ),
    ]
