# Generated by Django 5.2.8 on 2026-04-11 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloquea_a_tareas', to='tareas.tarea')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_configuradas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'dependencia de tarea',
                'verbose_name_plural': 'dependencias de tareas',
                'unique_together': {('tarea', 'depende_de')},
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='dependencias',
            field=models.ManyToManyField(blank=True, related_name='es_dependencia_de', through='tareas.TareaDependencia', to='tareas.tarea', verbose_name='Dependencias'),
        ),
    ]
