# Generated by Django 5.2.8 on 2026-04-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etiquetas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='etiqueta',
            unique_together={('nombre', 'proyecto')},
        ),
    ]
