# Generated by Django 5.2.8 on 2026-04-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'tablero',
                'verbose_name_plural': 'tableros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='tableros.tablero', verbose_name='Tablero')),
            ],
            options={
                'verbose_name': 'columna',
                'verbose_name_plural': 'columnas',
                'ordering': ['orden'],
            },
        ),
    ]
